### ISSUE TITLE
typeerror

### ISSUE THREAD

**Issue by folkertvanheusden** [outofmbufs/python-pdp11-emulator#21]
When I accidentely entered `rp(0,0)rpunix` instead of `hp(0,0)unix` I got the following error on the console:

```
Traceback (most recent call last):
  File "/home/folkert/t/python-pdp11-emulator/boot.py", line 394, in <module>
    boot_unix(p, runoptions=runoptions, **unixboot_options)
  File "/home/folkert/t/python-pdp11-emulator/boot.py", line 332, in boot_unix
    p.run(pc=0, **runoptions)
  File "/home/folkert/t/python-pdp11-emulator/machine.py", line 590, in run
    self.go_trap(self.get_synchronous_trap(abort_trap))
  File "/home/folkert/t/python-pdp11-emulator/machine.py", line 685, in go_trap
    self.logger.debug(f"TRAP: {trap}:\n{self.machinestate(fmt=oct)}")
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/folkert/t/python-pdp11-emulator/machine.py", line 1046, in machinestate
    pfx = '0' if v > 7 else ''
                 ^^^^^
TypeError: '>' not supported between instances of 'AddressError' and 'int'
```

**Comment by outofmbufs** [comment]
Bug in machinestate when using octal formatting for logging, because the result of reading what MMR2 points to can be an AddressError(). Fixed - but this also makes me wonder if doing that "invisible read" for logging is even a good idea at all.

Why it crashes: The boot.c code (from unix7) has a table of devices in it, and "rp" is one of those devices. Same thing would happen if you type any other known (to the bootstrap) device that isn't present. What happens now with this fix is that the boot code hits a halt instruction and exits the emulator (cleanly). In SIMH if you do this, the boot code hangs -- you never get a new prompt but at first glance I'm not sure where the boot code is hanging/looping (but doesn't seem to hit a halt instruction). This is pointing at some underlying difference that is probably another bug somewhere - maybe AddressError is the wrong trap in this situation? Not sure.
